version: '3.7'

services:
  frontend:
    mem_limit: 128m
    cpus: 0.1

    restart: unless-stopped
    image: ourspace-fe
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:80
  backend:
    mem_limit: 512M
    cpus: 0.2

    restart: unless-stopped
    image: ourspace-be
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - db
  db:
    mem_limit: 128m
    cpus: 0.05

    restart: unless-stopped
    image: 'postgres:10-alpine'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
